name: checkfast
description: CheckFast - Presença comprovada, pagamento garantido.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  excel: ^4.0.3 # Exportação em XLS
  google_mlkit_face_detection: ^0.10.0 # Anti-Fraude Facial
  flutter_local_notifications: ^17.0.0 # Alerta de Falta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
